### PR TITLE
fix: added Developer profile page

### PR DESCRIPTION
**Pull request by vineeth-cnbr**

### CODE REVIEW

**Comment by vineeth-cnbr** [comment]
image

Developer Page UI

**Comment by Utkarshbhimte** [comment]
resolves #1

**Comment by Utkarshbhimte** [comment]
image

Can you make the icon sizes same ie 1.3rem?

**Comment by Utkarshbhimte** [comment]
image
the vertical padding on the main header should be same as the card below.

**Comment by Utkarshbhimte** [comment]
image

There are 2 links one is a hosted app and another is GitHub code link? You should only show the project link here, the code link will be in the GitHub button.

**Comment by vineeth-cnbr** [comment]
> 
> 
> image
> 
> There are 2 links one is a hosted app and another is GitHub code link? You should only show the project link here, the code link will be in the GitHub button.

Yeah, I've added project link itself. In the database, i entered a github link as my projectlink. That is why it is coming like that

**Comment by vineeth-cnbr** [comment]
image

Is this good?

**Pull request merged**
